name: RunTests

on:
  push:
    branches: [ "!main" ]

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - run: npm ci
    - run: npm test
